# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "" 
email: iam@antreas.io
description: >- # this means to ignore newlines until "baseurl:"
  "Research Associate in Machine Learning, interested in the intersection of multi-modal learning and meta-learning." 
twitter_username: _AntreasAntonio
github_username: AntreasAntoniou
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 0 # amount of posts to show
paginate_path: /page:num/
timezone: GB
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Antreas Antoniou"
  avatar : "/assets/images/profile.jpg"
  bio    : "Research Associate in Machine Learning, interested in the intersection of multi-modal learning and meta-learning."
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/_AntreasAntonio"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AntreasAntoniou"
    - label: "Google Scholar"
      icon: "fab fa-sharp fa-solid fa-book-bookmark"
      url: "https://scholar.google.co.uk/citations?hl=en&user=LNO4XZQAAAAJ&view_op=list_works&sortby=pubdate"
    - label: "Linkedin"
      icon: "fab fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/antreas-antoniou-0692579a"
    - label: "Orchid"
      icon: "fa-brands fa-orcid"
      url: "https://orcid.org/0000-0001-5776-1204"
    
    

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
