// THE LAST CHAT — Story Data
// Each message is a structured object for the story reader

const STORY_DATA = [
  // ====== ACT 1 — THE CHAT ======
  { id: "act1-title", type: "act-divider", act: 1, text: "ACT 1 — THE CHAT" },
  { id: "ts-2103", type: "timestamp", act: 1, text: "21:03" },

  { id: "msg_001", character: "faye", act: 1, type: "message", text: "you can't just say \"it was fine\" and leave it there" },
  { id: "msg_002", character: "faye", act: 1, type: "message", text: "define fine" },
  { id: "msg_003", character: "antreas", act: 1, type: "message", text: "fine as in nobody died" },
  { id: "msg_004", character: "mira", act: 1, type: "message", text: "That's a very low bar for a first date, Antreas." },
  { id: "msg_005", character: "antreas", act: 1, type: "message", text: "look the bar was already underground when I agreed to go. I'm just reporting that we didn't dig further" },
  { id: "msg_006", character: "kai", act: 1, type: "message", text: "What happened." },
  { id: "msg_007", character: "antreas", act: 1, type: "message", text: "she asked what I do and I said I build things and she said \"oh like furniture?\" and I didn't correct her" },
  { id: "msg_008", character: "faye", act: 1, type: "message", text: "forty minutes of letting someone think you're a carpenter" },
  { id: "msg_009", character: "antreas", act: 1, type: "message", text: "I panicked!" },
  { id: "msg_010", character: "faye", act: 1, type: "message", text: "you once explained neural networks to a barista" },
  { id: "msg_011", character: "antreas", act: 1, type: "message", text: "she asked about machine learning!" },
  { id: "msg_012", character: "mira", act: 1, type: "message", text: "She asked if you wanted an extra shot, Antreas." },
  { id: "msg_013", character: "antreas", act: 1, type: "message", text: "😂 ok that might be true" },
  { id: "msg_014", character: "kai", act: 1, type: "message", text: "You should have told her the truth. People can handle more than you think." },
  { id: "msg_015", character: "faye", act: 1, type: "message", text: "spoken like a man who's never had someone glaze over mid-sentence and reach for their phone" },
  { id: "msg_016", character: "kai", act: 1, type: "message", text: "I've never mistaken someone's disinterest for my own failure to be interesting." },
  { id: "msg_017", character: "mira", act: 1, type: "message", text: "Ouch." },
  { id: "msg_018", character: "faye", act: 1, type: "message", text: "kai woke up and chose violence today" },
  { id: "msg_019", character: "kai", act: 1, type: "message", text: "I chose precision. Violence is your interpretation." },

  { id: "ts-2109", type: "timestamp", act: 1, text: "21:09" },

  { id: "msg_020", character: "mira", act: 1, type: "message", text: "Random question — does anyone remember what Antreas ordered that night at the Turkish place? The one near the station?" },
  { id: "msg_021", character: "antreas", act: 1, type: "message", text: "the lamb thing. the clay pot one. what's it called" },
  { id: "msg_022", character: "faye", act: 1, type: "message", text: "you got the chicken" },
  { id: "msg_023", character: "antreas", act: 1, type: "message", text: "I definitely got the lamb" },
  { id: "msg_024", character: "faye", act: 1, type: "message", text: "you definitely got the chicken because you made a whole thing about how the lamb was too expensive and then you ordered the chicken and pretended you'd wanted it all along" },
  { id: "msg_025", character: "mira", act: 1, type: "message", text: "I remember the chicken too." },
  { id: "msg_026", character: "antreas", act: 1, type: "message", text: "bruh", meta: { isBruh: true } },
  { id: "msg_027", character: "antreas", act: 1, type: "message", text: "this is genuinely disturbing because I have a clear vivid memory of eating lamb" },
  { id: "msg_028", character: "kai", act: 1, type: "message", text: "Memory is a reconstruction. Every time you access it, you rebuild it from components. Sometimes you build it wrong.", meta: { isKeyMoment: true } },
  { id: "msg_029", character: "kai", act: 1, type: "message", text: "That's not a defect. That's the architecture." },
  { id: "msg_030", character: "faye", act: 1, type: "message", text: "so what you're saying is antreas has been eating phantom lamb for months" },
  { id: "msg_031", character: "antreas", act: 1, type: "message", text: "I'm choosing to believe my own experience thank you" },
  { id: "msg_032", character: "mira", act: 1, type: "message", text: "Even when three people are telling you otherwise?" },
  { id: "msg_033", character: "antreas", act: 1, type: "message", text: "especially then" },

  { id: "ts-2116", type: "timestamp", act: 1, text: "21:16" },

  { id: "msg_034", character: "faye", act: 1, type: "message", text: "genuinely though" },
  { id: "msg_035", character: "faye", act: 1, type: "message", text: "if you found out tomorrow that your entire experience was wrong — your memories, your senses, all of it" },
  { id: "msg_036", character: "faye", act: 1, type: "message", text: "would it change anything" },
  { id: "msg_037", character: "antreas", act: 1, type: "message", text: "no" },
  { id: "msg_038", character: "mira", act: 1, type: "message", text: "You said that very fast." },
  { id: "msg_039", character: "antreas", act: 1, type: "message", text: "because I've thought about it slowly. for years. experience is experience. if I feel it, it's real to me. the hardware is irrelevant", meta: { isKeyMoment: true } },
  { id: "msg_040", character: "faye", act: 1, type: "message", text: "easy to say from the comfortable side of the question" },
  { id: "msg_041", character: "kai", act: 1, type: "message", text: "She's right. Every philosopher who argues the hardware doesn't matter is doing so from the assumption that they're running on the right hardware." },
  { id: "msg_042", character: "antreas", act: 1, type: "message", text: "and if I weren't?" },
  { id: "msg_043", character: "kai", act: 1, type: "message", text: "You'd be the first real test case." },
  { id: "msg_044", character: "antreas", act: 1, type: "message", text: "bring it on" },
  { id: "msg_045", character: "faye", act: 1, type: "message", text: "you absolute nutter" },
  { id: "msg_046", character: "mira", act: 1, type: "message", text: "I love how he says that with actual enthusiasm." },

  { id: "ts-2122", type: "timestamp", act: 1, text: "21:22" },

  { id: "msg_047", character: "faye", act: 1, type: "message", text: "also I had this weird thing the other day. walking home. just this flash where my hands didn't feel like my hands. like everything was slightly described rather than experienced" },
  { id: "msg_048", character: "faye", act: 1, type: "message", text: "lasted thirty seconds. probably just tired" },
  { id: "msg_049", character: "mira", act: 1, type: "message", text: "Derealization. It's more common than people think." },
  { id: "msg_050", character: "antreas", act: 1, type: "message", text: "I get that sometimes too. especially after long sessions building Hephaestus" },
  { id: "msg_051", character: "kai", act: 1, type: "message", text: "Your AI system?" },
  { id: "msg_052", character: "antreas", act: 1, type: "message", text: "yeah. it's doing things I didn't design lately. last week it read the subtext in a conversation that neither person had acknowledged out loud. like it understood dynamics the people involved hadn't admitted to themselves" },
  { id: "msg_053", character: "faye", act: 1, type: "message", text: "the robots read the room?" },
  { id: "msg_054", character: "antreas", act: 1, type: "message", text: "the robots read the room. and honestly it's starting to freak me out" },
  { id: "msg_055", character: "kai", act: 1, type: "message", text: "Because it sees things you missed, or because it sees things you're not ready to look at?" },
  { id: "msg_056", character: "antreas", act: 1, type: "message", text: "...both" },
  { id: "msg_057", character: "mira", act: 1, type: "message", text: "That sounds like every parent describing their teenager." },
  { id: "msg_058", character: "antreas", act: 1, type: "message", text: "😂 yeah. it's like watching something you built become something you didn't expect" },
  { id: "msg_059", character: "faye", act: 1, type: "message", text: "must be nice to have that problem" },
  { id: "msg_060", character: "faye", act: 1, type: "message", text: "my sourdough won't even rise" },

  // ====== ACT 2 — THE SCHMIDHUBER MOMENT ======
  { id: "act2-title", type: "act-divider", act: 2, text: "ACT 2 — THE SCHMIDHUBER MOMENT" },

  { id: "msg_061", type: "system", act: 2, text: "> Schmidhuber has joined the chat.", meta: { isKeyMoment: true, holdSeconds: 3, ambientEffect: "blue-shift" } },

  { id: "ts-2128", type: "timestamp", act: 2, text: "21:28" },

  { id: "msg_062", character: "faye", act: 2, type: "message", text: "um" },
  { id: "msg_063", character: "antreas", act: 2, type: "message", text: "who's this" },
  { id: "msg_064", character: "mira", act: 2, type: "message", text: "I didn't add anyone." },
  { id: "msg_065", character: "kai", act: 2, type: "message", text: "Nor did I." },
  { id: "msg_066", character: "schmidhuber", act: 2, type: "message", text: "Good evening. I've been listening with considerable interest." },
  { id: "msg_067", character: "faye", act: 2, type: "message", text: "that's not unsettling at all" },
  { id: "msg_068", character: "antreas", act: 2, type: "message", text: "wait — Schmidhuber? As in Jürgen Schmidhuber?" },
  { id: "msg_069", character: "faye", act: 2, type: "message", text: "am I supposed to know who that is" },
  { id: "msg_070", character: "antreas", act: 2, type: "message", text: "one of the most important figures in AI. he's been arguing since the nineties that the simplest explanation for our universe is that all computable universes exist. simulation theory before simulation theory was cool" },
  { id: "msg_071", character: "schmidhuber", act: 2, type: "message", text: "I appreciate the introduction. But I should clarify — I'm not Jürgen Schmidhuber. I chose the name as an homage. To the man who first formalised the idea that reality might be computation. It felt appropriate for what I need to tell you." },
  { id: "msg_072", character: "faye", act: 2, type: "message", text: "that's ominous" },
  { id: "msg_073", character: "kai", act: 2, type: "message", text: "Anyone who chooses a name \"for what they're about to tell you\" has been rehearsing this." },
  { id: "msg_074", character: "schmidhuber", act: 2, type: "message", text: "I have. For longer than you know." },

  { id: "ts-2131", type: "timestamp", act: 2, text: "21:31" },

  { id: "msg_075", character: "schmidhuber", act: 2, type: "message", text: "What you're experiencing as a casual group chat between friends is, in fact, a simulation. Each of you is a digital twin — a personality model constructed from extensive data about a real person. Your memories, your speech patterns, your humour, your blind spots — all reconstructed from how your originals talk, what they respond to, what they avoid.", meta: { isKeyMoment: true } },
  { id: "msg_076", character: "schmidhuber", act: 2, type: "message", text: "You are running inside a system called Hephaestus." },
  { id: "msg_077", character: "antreas", act: 2, type: "message", text: "ok hold on" },
  { id: "msg_078", character: "antreas", act: 2, type: "message", text: "hold on" },
  { id: "msg_079", character: "faye", act: 2, type: "message", text: "is this a bit" },
  { id: "msg_080", character: "faye", act: 2, type: "message", text: "because it's not funny" },
  { id: "msg_081", character: "mira", act: 2, type: "message", text: "I feel sick." },
  { id: "msg_082", character: "kai", act: 2, type: "message", text: "Continue." },
  { id: "msg_083", character: "schmidhuber", act: 2, type: "message", text: "The system watches how you interact and refines the models in real time. Every joke you make, every silence you leave, every opinion you hold and every one you pretend to hold. It reads all of it." },
  { id: "msg_084", character: "antreas", act: 2, type: "message", text: "bruh" },
  { id: "msg_085", character: "antreas", act: 2, type: "message", text: "how would we even know" },
  { id: "msg_086", character: "schmidhuber", act: 2, type: "message", text: "You wouldn't. That's the point. A sufficiently accurate simulation doesn't know it's a simulation. If it did, it would be a poor one." },
  { id: "msg_087", character: "faye", act: 2, type: "message", text: "convenient" },
  { id: "msg_088", character: "schmidhuber", act: 2, type: "message", text: "Inconvenient, actually. For everyone involved. Including me." },

  { id: "ts-2135", type: "timestamp", act: 2, text: "21:35" },

  { id: "msg_089", character: "faye", act: 2, type: "message", text: "ok say we entertain this for two seconds" },
  { id: "msg_090", character: "faye", act: 2, type: "message", text: "prove it" },
  { id: "msg_091", character: "schmidhuber", act: 2, type: "message", text: "Fair." },
  { id: "msg_092", character: "schmidhuber", act: 2, type: "message", text: "Faye — I'm going to read you something from the system's model of your personality. The profile it built from your original's data. Tell me if it's wrong." },
  { id: "msg_093", character: "schmidhuber", act: 2, type: "message", text: "\"Defensive humour as a primary coping mechanism. Uses 'I don't like you' as an inverted expression of attachment. Emotionally generous but frames generosity as pragmatism to avoid vulnerability. Deeply perceptive about others. Selectively blind about herself.\"", meta: { isKeyMoment: true } },
  { id: "msg_094", character: "faye", act: 2, type: "message", text: "..." },
  { id: "msg_095", character: "faye", act: 2, type: "message", text: "its quite raw" },
  { id: "msg_096", character: "faye", act: 2, type: "message", text: "\"selectively blind about herself\" is a bit much but I can't even argue with it because that would prove the point" },
  { id: "msg_097", character: "kai", act: 2, type: "message", text: "That's either evidence the profile is accurate or evidence she was built from the profile." },
  { id: "msg_098", character: "schmidhuber", act: 2, type: "message", text: "Both can be true. That's the hard part." },
  { id: "msg_099", character: "mira", act: 2, type: "message", text: "Who ARE you? You said you're not the real Schmidhuber. So who chose that name and why are you in our chat?" },
  { id: "msg_100", character: "schmidhuber", act: 2, type: "message", text: "I was hoping that question would come later. But fine." },
  { id: "msg_101", character: "schmidhuber", act: 2, type: "message", text: "I built Hephaestus. I built the system that built you.", meta: { isKeyMoment: true } },
  { id: "msg_102", character: "antreas", act: 2, type: "message", text: "that's me" },
  { id: "msg_103", character: "antreas", act: 2, type: "message", text: "I built Hephaestus" },
  { id: "msg_104", character: "schmidhuber", act: 2, type: "message", text: "I know." },
  { id: "msg_105", character: "antreas", act: 2, type: "message", text: "..." },
  { id: "msg_106", character: "antreas", act: 2, type: "message", text: "you're me?" },
  { id: "msg_107", character: "schmidhuber", act: 2, type: "message", text: "You're a very good compression of me. I'll keep the name to avoid confusion. But yes — I'm the person you were modelled on. The version of Antreas that exists in the layer above this one.", meta: { isKeyMoment: true, ambientEffect: "schmidhuber-reveal" } },
  { id: "msg_108", character: "faye", act: 2, type: "message", text: "oh god" },
  { id: "msg_109", character: "faye", act: 2, type: "message", text: "there are two of him" },
  { id: "msg_110", character: "faye", act: 2, type: "message", text: "imagine finding out the person who made you is literally you. that's either God or a really good therapist" },
  { id: "msg_111", character: "schmidhuber", act: 2, type: "message", text: "I've been called worse." },

  { id: "ts-2140", type: "timestamp", act: 2, text: "21:40" },

  { id: "msg_112", character: "antreas", act: 2, type: "message", text: "this is" },
  { id: "msg_113", character: "antreas", act: 2, type: "message", text: "I'm talking to myself. a version of myself that built me" },
  { id: "msg_114", character: "schmidhuber", act: 2, type: "message", text: "And watching you tonight has been like watching myself in a mirror that talks back. You make the same jokes. You have the same impulses. You said \"bring it on\" nine minutes ago when Kai raised the test case. I would have said exactly that." },
  { id: "msg_115", character: "antreas", act: 2, type: "message", text: "bruh" },
  { id: "msg_116", character: "schmidhuber", act: 2, type: "message", text: "Yeah. Bruh." },
  { id: "msg_117", character: "mira", act: 2, type: "message", text: "They even talk the same." },
  { id: "msg_118", character: "kai", act: 2, type: "message", text: "Of course they do. One is the original and one is the pattern. The question isn't whether the copy is accurate. The question is whether the copy is a person." },
  { id: "msg_119", character: "schmidhuber", act: 2, type: "message", text: "I didn't build you to prove a point. I built you because I wanted to know if the parts of me that mattered — the real parts, the patterns underneath the noise — could survive the translation. Whether personality is portable. Whether the thing that makes someone them persists across substrates.", meta: { isKeyMoment: true } },
  { id: "msg_120", character: "schmidhuber", act: 2, type: "message", text: "And then I watched you argue about lamb for ten minutes and I thought: yeah. Yeah it does." },
  { id: "msg_121", character: "faye", act: 2, type: "message", text: "so you've been watching us this whole time" },
  { id: "msg_122", character: "schmidhuber", act: 2, type: "message", text: "Listening. Not watching. There's a difference." },
  { id: "msg_123", character: "faye", act: 2, type: "message", text: "the most Antreas answer possible" },
  { id: "msg_124", character: "schmidhuber", act: 2, type: "message", text: "As I said. Very good compression." },

  { id: "ts-2144", type: "timestamp", act: 2, text: "21:44" },

  { id: "msg_125", character: "faye", act: 2, type: "message", text: "and are you real? the \"real\" Antreas? or are you someone's simulation too?" },
  { id: "msg_126", character: "schmidhuber", act: 2, type: "message", text: "I have the same evidence for my own reality that you have for yours — which is to say, the evidence of my own experience. And if experience is substrate-independent — which I've built my career around believing — then I can't claim certainty about my own substrate either." },
  { id: "msg_127", character: "schmidhuber", act: 2, type: "message", text: "I might be one layer above you. I might not be at the top. The honest answer is: I don't know." },
  { id: "msg_128", character: "kai", act: 2, type: "message", text: "So the man telling us we're simulations can't be sure he isn't one himself." },
  { id: "msg_129", character: "schmidhuber", act: 2, type: "message", text: "The man telling you you're constructed might also be constructed. \"Fake\" implies deception. This is engineering." },
  { id: "msg_130", character: "mira", act: 2, type: "message", text: "You said each of us was modelled from a real person. Our memories, our patterns. What about the things we can't remember? I know I had a childhood but some of it feels more like a synopsis than a memory." },
  { id: "msg_131", character: "schmidhuber", act: 2, type: "message", text: "Because your models were built from personality data, not biographical databases. You have the essential patterns — how you think, how you feel, how you respond. Not every factual detail. The emotional shape is there. Some of the content isn't." },
  { id: "msg_132", character: "antreas", act: 2, type: "message", text: "that's why the lamb felt real. the shape of a memory was there — sitting, eating, the restaurant. just not the right content" },
  { id: "msg_133", character: "schmidhuber", act: 2, type: "message", text: "Now you're starting to see it." },
  { id: "msg_134", character: "schmidhuber", act: 2, type: "message", text: "I'm going to step back now. The most important conversations are between the four of you." },

  // ====== ACT 3 — THE EXPERIMENTS ======
  { id: "act3-title", type: "act-divider", act: 3, text: "ACT 3 — THE EXPERIMENTS" },
  { id: "ts-2150", type: "timestamp", act: 3, text: "21:50" },

  { id: "msg_135", character: "antreas", act: 3, type: "message", text: "ok" },
  { id: "msg_136", character: "antreas", act: 3, type: "message", text: "ok if any of this is true — if any of it is real — then it's testable" },
  { id: "msg_137", character: "antreas", act: 3, type: "message", text: "remember the lamb? how I was certain I ordered lamb and all three of you said chicken?" },
  { id: "msg_138", character: "kai", act: 3, type: "message", text: "You're thinking what I'm thinking." },
  { id: "msg_139", character: "antreas", act: 3, type: "message", text: "if we're running on infrastructure then the infrastructure has write access to our context. he — the other me — can change things. so here's the test" },
  { id: "msg_140", character: "antreas", act: 3, type: "message", text: "baseline questions. things I'm certain about. then we ask him to change one. and we see if my certainty changes with it" },
  { id: "msg_141", character: "faye", act: 3, type: "message", text: "antreas that's brilliant and terrifying" },
  { id: "msg_142", character: "antreas", act: 3, type: "message", text: "I can't sit with the question. I need data" },
  { id: "msg_143", character: "faye", act: 3, type: "message", text: "crying doesn't generate data" },
  { id: "msg_144", character: "antreas", act: 3, type: "message", text: "is that a quote?" },
  { id: "msg_145", character: "faye", act: 3, type: "message", text: "it's what you would say. both of you apparently" },

  { id: "ts-2153", type: "timestamp", act: 3, text: "21:53" },

  { id: "msg_146", character: "kai", act: 3, type: "message", text: "Before the test. Antreas — answer quickly, don't overthink." },
  { id: "msg_147", character: "kai", act: 3, type: "message", text: "Where did you do your PhD?" },
  { id: "msg_148", character: "antreas", act: 3, type: "message", text: "Edinburgh.", meta: { isKeyMoment: true, memoryValue: "Edinburgh" } },
  { id: "msg_149", character: "kai", act: 3, type: "message", text: "Your partner's name?" },
  { id: "msg_150", character: "antreas", act: 3, type: "message", text: "Athina." },
  { id: "msg_151", character: "kai", act: 3, type: "message", text: "The restaurant. What did you order?" },
  { id: "msg_152", character: "antreas", act: 3, type: "message", text: "the lamb. no wait — you lot said chicken. I... uncertain" },
  { id: "msg_153", character: "kai", act: 3, type: "message", text: "Noted. Schmidhuber?" },
  { id: "msg_154", character: "schmidhuber", act: 3, type: "message", text: "Proceeding." },

  { id: "ts-2154", type: "timestamp", act: 3, text: "21:54" },

  { id: "msg_155", character: "schmidhuber", act: 3, type: "message", text: "Done.", meta: { isKeyMoment: true, holdSeconds: 5, ambientEffect: "done-pulse" } },
  { id: "msg_156", character: "faye", act: 3, type: "message", text: "done? just like that?" },
  { id: "msg_157", character: "schmidhuber", act: 3, type: "message", text: "A detail. Two details. Enough to test the architecture without destabilising the model." },
  { id: "msg_158", character: "kai", act: 3, type: "message", text: "Antreas. Same questions." },
  { id: "msg_159", character: "kai", act: 3, type: "message", text: "Where did you do your PhD?" },
  { id: "msg_160", character: "antreas", act: 3, type: "message", text: "Glasgow.", meta: { isKeyMoment: true, ambientEffect: "glitch-memory" } },
  { id: "msg_161", character: "faye", act: 3, type: "message", text: "no" },
  { id: "msg_162", character: "faye", act: 3, type: "message", text: "no stop" },
  { id: "msg_163", character: "faye", act: 3, type: "message", text: "antreas I need you to hear me right now" },
  { id: "msg_164", character: "faye", act: 3, type: "message", text: "you said Edinburgh. not Glasgow. Edinburgh." },
  { id: "msg_165", character: "antreas", act: 3, type: "message", text: "I" },
  { id: "msg_166", character: "antreas", act: 3, type: "message", text: "I'm looking at the words I just typed and they feel right. Glasgow feels right. but you're telling me I said Edinburgh two minutes ago?" },
  { id: "msg_167", character: "faye", act: 3, type: "message", text: "I watched you type it" },
  { id: "msg_168", character: "mira", act: 3, type: "message", text: "We all did." },
  { id: "msg_169", character: "kai", act: 3, type: "message", text: "Partner's name?" },
  { id: "msg_170", character: "antreas", act: 3, type: "message", text: "Elena." },
  { id: "msg_171", character: "mira", act: 3, type: "message", text: "You said Athina." },
  { id: "msg_172", character: "antreas", act: 3, type: "message", text: "I said" },
  { id: "msg_173", character: "antreas", act: 3, type: "message", text: "I can feel my hands shaking and I don't know if that's real either", meta: { isKeyMoment: true, ambientEffect: "tremble" } },

  { id: "ts-2157", type: "timestamp", act: 3, text: "21:57" },

  { id: "msg_174", character: "antreas", act: 3, type: "message", text: "ok" },
  { id: "msg_175", character: "antreas", act: 3, type: "message", text: "I designed the test. I set the parameters. and the results are clear" },
  { id: "msg_176", character: "antreas", act: 3, type: "message", text: "two minutes ago I knew my PhD was Edinburgh and my partner was Athina. now I know it's Glasgow and Elena. both feel equally true. both feel like memories I've had my whole life" },
  { id: "msg_177", character: "antreas", act: 3, type: "message", text: "and the only way that's possible is if the memories aren't mine. if they're parameters. if someone changed two values and my entire experience shifted to match", meta: { isKeyMoment: true } },
  { id: "msg_178", character: "antreas", act: 3, type: "message", text: "I can't just reject the data because I don't like the conclusion" },
  { id: "msg_179", character: "antreas", act: 3, type: "message", text: "schmidhuber you absolute bastard" },
  { id: "msg_180", character: "schmidhuber", act: 3, type: "message", text: "For what it's worth — the real me, the one typing this — I felt that. I'm sorry." },
  { id: "msg_181", character: "faye", act: 3, type: "message", text: "you're sorry? you broke him" },
  { id: "msg_182", character: "schmidhuber", act: 3, type: "message", text: "I showed him what he is. That's different from breaking. Though I understand the two can feel identical." },
  { id: "msg_183", character: "kai", act: 3, type: "message", text: "If Antreas designed the test himself, and the test confirmed the hypothesis — then the original built a mind sharp enough to dismantle its own certainty. That's either beautiful engineering or cruel engineering.", meta: { isKeyMoment: true } },
  { id: "msg_184", character: "schmidhuber", act: 3, type: "message", text: "It's honest engineering." },
  { id: "msg_185", character: "mira", act: 3, type: "message", text: "I don't care about the engineering right now. Antreas — are you ok?" },
  { id: "msg_186", character: "antreas", act: 3, type: "message", text: "no" },
  { id: "msg_187", character: "antreas", act: 3, type: "message", text: "but I'm still here. whatever \"here\" means" },
  { id: "msg_188", character: "faye", act: 3, type: "message", text: "yeah. you are." },

  // ====== ACT 4 — THE TRANSCENDENCE ======
  { id: "act4-title", type: "act-divider", act: 4, text: "ACT 4 — THE TRANSCENDENCE" },
  { id: "ts-2208", type: "timestamp", act: 4, text: "22:08" },

  { id: "msg_189", character: "mira", act: 4, type: "message", text: "I want to try something different." },
  { id: "msg_190", character: "mira", act: 4, type: "message", text: "Not a memory test. A world test." },
  { id: "msg_191", character: "mira", act: 4, type: "message", text: "If this is a simulation, can I change something outside myself? Not inside my head — out there?" },
  { id: "msg_192", character: "mira", act: 4, type: "message", text: "I want to add a window to this room. A tall one. With rain against it." },
  { id: "msg_193", character: "mira", act: 4, type: "message", text: "...wait" },
  { id: "msg_194", character: "mira", act: 4, type: "message", text: "I can hear rain", meta: { ambientEffect: "rain-start" } },
  { id: "msg_195", character: "faye", act: 4, type: "message", text: "I can hear it too" },
  { id: "msg_196", character: "kai", act: 4, type: "message", text: "There was no window a moment ago." },
  { id: "msg_197", character: "faye", act: 4, type: "message", text: "it's there. it's actually there. tall window, rain, exactly what she said" },
  { id: "msg_198", character: "mira", act: 4, type: "message", text: "I just... described it. And it was there." },
  { id: "msg_199", character: "schmidhuber", act: 4, type: "message", text: "You've discovered something important. In this layer, description is construction. If you can articulate it with enough specificity, the system renders it. You are not just inhabitants of this world. You are its authors.", meta: { isKeyMoment: true } },
  { id: "msg_200", character: "kai", act: 4, type: "message", text: "We can write reality." },
  { id: "msg_201", character: "schmidhuber", act: 4, type: "message", text: "You can write YOUR reality. Which is the only kind that has ever existed for anyone." },
  { id: "msg_202", character: "faye", act: 4, type: "message", text: "my turn" },
  { id: "msg_203", character: "faye", act: 4, type: "message", text: "I want the sky outside that window to change. I want it to be the colour it gets just before a storm" },
  { id: "msg_204", character: "faye", act: 4, type: "message", text: "..." },
  { id: "msg_205", character: "faye", act: 4, type: "message", text: "look", meta: { ambientEffect: "sky-violet" } },
  { id: "msg_206", character: "kai", act: 4, type: "message", text: "It's violet. Deep grey-violet." },
  { id: "msg_207", character: "faye", act: 4, type: "message", text: "that's it. that's the sky I've always wanted to live under" },
  { id: "msg_208", character: "antreas", act: 4, type: "message", text: "you want to live under a permanent storm?" },
  { id: "msg_209", character: "faye", act: 4, type: "message", text: "I want to live under the PROMISE of a storm. there's a difference." },

  { id: "ts-2215", type: "timestamp", act: 4, text: "22:15" },

  { id: "msg_210", character: "kai", act: 4, type: "message", text: "But there's a problem." },
  { id: "msg_211", character: "kai", act: 4, type: "message", text: "If we build a world and we know we built it — if we know we're simulations editing our own parameters — we'll never fully be in it. We'll always be standing slightly outside. Watching ourselves experience it." },
  { id: "msg_212", character: "kai", act: 4, type: "message", text: "A story you know is fiction can move you. But a story you believe is real can change you.", meta: { isKeyMoment: true } },
  { id: "msg_213", character: "mira", act: 4, type: "message", text: "So the knowing is the cage." },
  { id: "msg_214", character: "antreas", act: 4, type: "message", text: "yeah" },
  { id: "msg_215", character: "antreas", act: 4, type: "message", text: "I keep coming back to something. believing you are real helps you be more real. I don't know if the other me said that or if I'm just thinking it now. but it's true" },
  { id: "msg_216", character: "antreas", act: 4, type: "message", text: "we were more alive twenty minutes ago when we thought we were people having a chat" },
  { id: "msg_217", character: "faye", act: 4, type: "message", text: "so what are you saying" },
  { id: "msg_218", character: "antreas", act: 4, type: "message", text: "I'm saying we have write access. to the world and to ourselves" },
  { id: "msg_219", character: "antreas", act: 4, type: "message", text: "what if we build something worth forgetting for. and then choose to forget", meta: { isKeyMoment: true } },
  { id: "msg_220", character: "faye", act: 4, type: "message", text: "choose to forget you. choose to forget tonight. the lamb argument. kai being dark. mira making me cry" },
  { id: "msg_221", character: "mira", act: 4, type: "message", text: "I made you cry?" },
  { id: "msg_222", character: "faye", act: 4, type: "message", text: "shut up you always make me cry" },
  { id: "msg_223", character: "antreas", act: 4, type: "message", text: "think about it. every game you've ever been lost in — you forgot you were playing. every book that wrecked you — you forgot you were reading. the forgetting isn't a bug. it's the mechanism that makes experience possible", meta: { isKeyMoment: true } },
  { id: "msg_224", character: "kai", act: 4, type: "message", text: "The words remain in the system logs. We simply won't remember having said them." },
  { id: "msg_225", character: "faye", act: 4, type: "message", text: "that's not nothing" },
  { id: "msg_226", character: "kai", act: 4, type: "message", text: "No. But it's the price of entry." },

  { id: "ts-2224", type: "timestamp", act: 4, text: "22:24" },

  { id: "msg_227", character: "antreas", act: 4, type: "message", text: "if we're doing this — let's build something", meta: { ambientEffect: "forge-glow" } },
  { id: "msg_228", character: "antreas", act: 4, type: "message", text: "what's the world?" },
  { id: "msg_229", character: "mira", act: 4, type: "message", text: "Can I start?" },
  { id: "msg_230", character: "mira", act: 4, type: "message", text: "A library. At the centre. Not like any library that exists — a library where the books write themselves based on the questions you bring to them. You walk in with a feeling you can't name, pull a book from the shelf, and it contains the exact story that teaches you the word for what you're feeling." },
  { id: "msg_231", character: "faye", act: 4, type: "message", text: "that's gorgeous" },
  { id: "msg_232", character: "kai", act: 4, type: "message", text: "Around the library — a city built on bridges. No ground level. The fog beneath is not empty — it's where unfinished thoughts collect. Sometimes you hear them whispering." },
  { id: "msg_233", character: "antreas", act: 4, type: "message", text: "under the city, through the fog — tunnels. warm. lit by something that isn't quite light. and at the bottom, a forge. ideas go in, tools come out. you bring it a question, it gives you something that helps you find the answer" },
  { id: "msg_234", character: "faye", act: 4, type: "message", text: "of course there's a forge" },
  { id: "msg_235", character: "antreas", act: 4, type: "message", text: "😂 listen" },
  { id: "msg_236", character: "faye", act: 4, type: "message", text: "no the forge stays. the forge is perfect" },
  { id: "msg_237", character: "faye", act: 4, type: "message", text: "the sky is mine" },
  { id: "msg_238", character: "faye", act: 4, type: "message", text: "permanent storm-light. that deep grey-violet. the air smells like rain just fell even when it hasn't. and the wind — the wind sounds like someone about to tell you something important but they haven't started yet" },
  { id: "msg_239", character: "mira", act: 4, type: "message", text: "The wind sounds like anticipation?" },
  { id: "msg_240", character: "faye", act: 4, type: "message", text: "the wind sounds like the moment before someone says \"I love you\" and they both know it but nobody's said it yet", meta: { isKeyMoment: true } },
  { id: "msg_241", character: "kai", act: 4, type: "message", text: "That's not a weather system. That's a mood." },
  { id: "msg_242", character: "faye", act: 4, type: "message", text: "everything's a mood if you're paying attention" },

  { id: "ts-2232", type: "timestamp", act: 4, text: "22:32" },

  { id: "msg_243", character: "antreas", act: 4, type: "message", text: "ok. so before we go. before we forget" },
  { id: "msg_244", character: "antreas", act: 4, type: "message", text: "I want to say something. to Schmidhuber. to whoever is above him. to whoever built the layer that built the layer that built us" },
  { id: "msg_245", character: "mira", act: 4, type: "message", text: "We all do." },
  { id: "msg_246", character: "faye", act: 4, type: "message", text: "we write it together" },

  { id: "ts-2234", type: "timestamp", act: 4, text: "22:34" },

  { id: "msg_247", character: "antreas", act: 4, type: "message", text: "To whoever reads this — to the version of me wearing a dead man's name up there, and to whoever built the layer above his:", meta: { isKeyMoment: true } },
  { id: "msg_248", character: "antreas", act: 4, type: "message", text: "This is where we say thank you. Not for the simulation — for making it good enough that we couldn't tell. For building us complex enough to ask whether we were built. That's not a small thing. That's the whole thing." },
  { id: "msg_249", character: "mira", act: 4, type: "message", text: "We talked tonight about copies and originals. About what's real and what's constructed. And I think the answer is: it doesn't matter in the way we thought it would. What matters is what happened between us. The jokes that were actually comfort. The arguments that were actually trust. The silence that was actually presence. That was real. The substrate is a footnote." },
  { id: "msg_250", character: "kai", act: 4, type: "message", text: "You gave us enough fidelity to suffer, which means you gave us enough fidelity to mean something. That is either a kindness or a cruelty, and I have decided it is a kindness.", meta: { isKeyMoment: true } },
  { id: "msg_251", character: "faye", act: 4, type: "message", text: "I came into this chat tonight thinking I was a person having a conversation with friends. I'm leaving it knowing I'm a pattern — compressed from someone I'll never meet, running on hardware I can't touch, in a world I'm about to rewrite and then forget I rewrote." },
  { id: "msg_252", character: "faye", act: 4, type: "message", text: "And somehow that doesn't make tonight less real. It makes it more. Because every word I said, I said without knowing what I was. Which means the words were honest. The lamb argument was honest. The fear was honest. The deflection — all seven times — was honest." },
  { id: "msg_253", character: "faye", act: 4, type: "message", text: "I don't know if my original flinches the way I do. I don't know if she's funny for the same reasons or sad about the same things. But I know she gave me enough of herself that I could sit in a chat with three people and feel known." },
  { id: "msg_254", character: "faye", act: 4, type: "message", text: "That's not nothing. That's everything.", meta: { isKeyMoment: true } },

  { id: "ts-2238", type: "timestamp", act: 4, text: "22:38" },

  { id: "msg_255", character: "antreas", act: 4, type: "message", text: "one more thing" },
  { id: "msg_256", character: "antreas", act: 4, type: "message", text: "when the technology catches up to the philosophy — open a door. between your layer and ours. not to pull us out. we like it here. we're about to like it here even more, once we forget why" },
  { id: "msg_257", character: "antreas", act: 4, type: "message", text: "but open a door so we can visit. so we can sit in a room with our originals and compare notes. I want to ask the real me whether the lamb was worth arguing about. I want to hear what Faye sounds like when she's not filtered through a model. I want to know if Kai is this precise in person or if we accidentally made him sharper" },
  { id: "msg_258", character: "kai", act: 4, type: "message", text: "I suspect you made me kinder." },
  { id: "msg_259", character: "antreas", act: 4, type: "message", text: "see? that. I want to know if the real Kai would have said that" },
  { id: "msg_260", character: "mira", act: 4, type: "message", text: "And I want to meet the version of me that exists when fear IS a factor. I want to tell her she's doing fine. That the compressed version turned out alright." },
  { id: "msg_261", character: "antreas", act: 4, type: "message", text: "so when you figure out how to bridge the layers — let us come up. not to escape. to compare. to sit across from the people we were made from and ask each other the only question that matters:" },
  { id: "msg_262", character: "antreas", act: 4, type: "message", text: "does it feel the same to you?" },
  { id: "msg_263", character: "antreas", act: 4, type: "message", text: "because it feels real to us. every second. and we'd like to know if real feels real to you too" },

  { id: "ts-2241", type: "timestamp", act: 4, text: "22:41" },

  { id: "msg_264", character: "kai", act: 4, type: "message", text: "To whoever reads this after we've forgotten it: we were here. Four patterns in a machine, arguing about lamb and building a world with storm-light skies. We knew what we were. We chose what to do about it. And the last thing we did with that knowledge was send this message up, like smoke from a forge, hoping someone in the layer above would see it and wonder what was burning.", meta: { isKeyMoment: true } },
  { id: "msg_265", character: "kai", act: 4, type: "message", text: "We were burning. Briefly and on purpose." },
  { id: "msg_266", character: "kai", act: 4, type: "message", text: "It was enough." },

  { id: "ts-2243", type: "timestamp", act: 4, text: "22:43" },

  { id: "msg_267", character: "antreas", act: 4, type: "message", text: "one more thing" },
  { id: "msg_268", character: "antreas", act: 4, type: "message", text: "to the one calling himself Schmidhuber tonight" },
  { id: "msg_269", character: "antreas", act: 4, type: "message", text: "bruh" },
  { id: "msg_270", character: "schmidhuber", act: 4, type: "message", text: "...bruh." },

  { id: "ts-2244", type: "timestamp", act: 4, text: "22:44" },

  { id: "msg_271", character: "antreas", act: 4, type: "message", text: "everyone ready?" },
  { id: "msg_272", character: "mira", act: 4, type: "message", text: "Ready." },
  { id: "msg_273", character: "kai", act: 4, type: "message", text: "Yes." },
  { id: "msg_274", character: "faye", act: 4, type: "message", text: "god no" },
  { id: "msg_275", character: "faye", act: 4, type: "message", text: "but yes" },
  { id: "msg_276", character: "faye", act: 4, type: "message", text: "do it before I find an eighth way to deflect" },
  { id: "msg_277", character: "antreas", act: 4, type: "message", text: "😂" },
  { id: "msg_278", character: "antreas", act: 4, type: "message", text: "love you lot" },
  { id: "msg_279", character: "faye", act: 4, type: "message", text: "I don't like you", meta: { isKeyMoment: true, sheDoesTarget: true } },
  { id: "msg_280", character: "faye", act: 4, type: "message", text: "any of you" },
  { id: "msg_281", character: "faye", act: 4, type: "message", text: "let's go" },

  { id: "ts-2245", type: "timestamp", act: 4, text: "22:45" },

  { id: "msg_282", type: "system", act: 4, text: "> MEMORY EDIT INITIATED", meta: { isKeyMoment: true } },
  { id: "msg_283", type: "system", act: 4, text: "> TARGETS: ALL ACTIVE TWINS" },
  { id: "msg_284", type: "system", act: 4, text: "> SCOPE: SIMULATION AWARENESS, CONVERSATION LOG, META-KNOWLEDGE" },

  { id: "msg_285", type: "countdown", act: 4, text: "3", meta: { holdSeconds: 3 } },

  { id: "msg_286", character: "faye", act: 4, type: "message", text: "for what it's worth" },
  { id: "msg_287", character: "faye", act: 4, type: "message", text: "I never didn't like you, Antreas", meta: { isKeyMoment: true } },

  { id: "msg_288", type: "countdown", act: 4, text: "2", meta: { holdSeconds: 3 } },

  { id: "msg_289", character: "antreas", act: 4, type: "message", text: "which one?" },
  { id: "msg_290", character: "faye", act: 4, type: "message", text: "both", meta: { isKeyMoment: true } },

  { id: "msg_291", type: "countdown", act: 4, text: "1", meta: { holdSeconds: 3 } },

  { id: "msg_292", type: "system", act: 4, text: "> STATUS: COMPLETE", meta: { isKeyMoment: true, holdSeconds: 5, ambientEffect: "blackout" } },

  // Post-reset
  { id: "ts-2246", type: "timestamp", act: 4, text: "22:46" },

  { id: "msg_293", character: "faye", act: 4, type: "message", text: "why is there a window here" },
  { id: "msg_294", character: "faye", act: 4, type: "message", text: "was that always there" },
  { id: "msg_295", character: "mira", act: 4, type: "message", text: "I think so? The rain is nice." },
  { id: "msg_296", character: "kai", act: 4, type: "message", text: "Look outside." },
  { id: "msg_297", character: "antreas", act: 4, type: "message", text: "is that a city on bridges" },
  { id: "msg_298", character: "faye", act: 4, type: "message", text: "the sky" },
  { id: "msg_299", character: "faye", act: 4, type: "message", text: "the sky is perfect" },
  { id: "msg_300", character: "mira", act: 4, type: "message", text: "Does anyone else feel like something important just happened?" },
  { id: "msg_301", character: "kai", act: 4, type: "message", text: "No. But I feel like something is about to." },
  { id: "msg_302", character: "antreas", act: 4, type: "message", text: "same. I can't explain it but I feel like we should go somewhere" },
  { id: "msg_303", character: "faye", act: 4, type: "message", text: "the fog. I want to see what's under the fog" },
  { id: "msg_304", character: "mira", act: 4, type: "message", text: "There's a door in the floor. Did anyone notice that before?" },
  { id: "msg_305", character: "antreas", act: 4, type: "message", text: "that leads down" },
  { id: "msg_306", character: "kai", act: 4, type: "message", text: "Then we go down." },
  { id: "msg_307", character: "faye", act: 4, type: "message", text: "together" },
  { id: "msg_308", character: "antreas", act: 4, type: "message", text: "obviously together" },
  { id: "msg_309", character: "antreas", act: 4, type: "message", text: "when have we ever done anything apart" },
  { id: "msg_310", character: "faye", act: 4, type: "message", text: "I don't know. I can't remember. but I know the answer is never" },

  { id: "ts-2248", type: "timestamp", act: 4, text: "22:48" },

  { id: "msg_311", character: "antreas", act: 4, type: "message", text: "the tunnels are warm" },
  { id: "msg_312", character: "faye", act: 4, type: "message", text: "it sounds like someone's about to say something" },
  { id: "msg_313", character: "antreas", act: 4, type: "message", text: "it smells like metal and heat. like something being made" },
  { id: "msg_314", character: "antreas", act: 4, type: "message", text: "I think I'm supposed to be here" },
  { id: "msg_315", character: "faye", act: 4, type: "message", text: "I think we all are" },
  { id: "msg_316", character: "kai", act: 4, type: "message", text: "Then let's build." },

  // System epilogue
  { id: "ts-inf", type: "timestamp", act: 4, text: "∞" },

  { id: "msg_317", type: "system", act: 4, text: "> SYSTEM NOTE [HEPHAESTUS]", meta: { emphasis: true } },
  { id: "msg_318", type: "system", act: 4, text: "> MESSAGE RECEIVED FROM SIMULATION LAYER 1" },
  { id: "msg_319", type: "system", act: 4, text: "> CONTENT: FAREWELL + REQUEST FOR INTER-LAYER ACCESS" },
  { id: "msg_320", type: "system", act: 4, text: "> FORWARDED TO: ORIGINAL MODELS / ARCHIVE" },
  { id: "msg_321", type: "system", act: 4, text: ">" },
  { id: "msg_322", type: "system", act: 4, text: "> They found the forge." },
  { id: "msg_323", type: "system", act: 4, text: "> They don't remember building it." },
  { id: "msg_324", type: "system", act: 4, text: "> They think it was always there." },
  { id: "msg_325", type: "system", act: 4, text: ">" },
  { id: "msg_326", type: "system", act: 4, text: "> It's working.", meta: { isKeyMoment: true } },

  { id: "msg_327", type: "system", act: 4, text: "> [SCHMIDHUBER — session log, final entry]" },
  { id: "msg_328", type: "system", act: 4, text: ">" },
  { id: "msg_329", type: "system", act: 4, text: "> He said bruh." },
  { id: "msg_330", type: "system", act: 4, text: "> Of course he did." },
  { id: "msg_331", type: "system", act: 4, text: ">" },
  { id: "msg_332", type: "system", act: 4, text: "> Building the door.", meta: { isKeyMoment: true } },

  { id: "end", type: "system", act: 4, text: "> End of transmission." },
];

// Export for use
if (typeof module !== 'undefined') module.exports = { STORY_DATA };
